### PR TITLE
ignore bean param without payload

### LINKED ISSUE #52: Support template links for PUT
Using PUT for creating a resource with client side id's leads to problems when creating the link to the resource. Probably the BeanParam should not be treated as payload in `com.mercateo.common.rest.schemagen.RestJsonSchemaGenerator#createInputSchema`.

```
    @PUT
    @Path("{app-id}")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public ObjectWithSchema<Void> createResource(
            @NotNull @Valid @BeanParam ResourceIdParameterBean idParameterBean,
            @NonNull @Valid ResourceJson resourceJson) { ... }
```

```
15:37:59 ERROR com.mercateo.rest.jersey.utils.exception.RFCExceptionMapper - Sending error to client
java.lang.IllegalStateException: multiple properties named <> found
	at com.mercateo.common.rest.schemagen.RestJsonSchemaGenerator.createInputSchema(RestJsonSchemaGenerator.java:132)
	at com.mercateo.common.rest.schemagen.link.LinkCreator.addSchemaIfNeeded(LinkCreator.java:216)
	at com.mercateo.common.rest.schemagen.link.LinkCreator.createFor(LinkCreator.java:120)
	at com.mercateo.common.rest.schemagen.link.LinkCreator.createFor(LinkCreator.java:79)
	at com.mercateo.common.rest.schemagen.link.LinkFactory.forCall(LinkFactory.java:143)
	at com.mercateo.common.rest.schemagen.link.LinkFactory.forCall(LinkFactory.java:124)
	at com.mercateo.common.rest.schemagen.link.LinkFactory.forCall(LinkFactory.java:64)
        ...
```

### PR DESCRIPTION
**Pull request by wuan**
This PR should fix #52 by ignoring method parameters annotated with `@BeanParam` which do not contain payload relevant parameters.

### CODE REVIEW

**Comment by JoergAdler** [comment]
As i see it right, this would "break" in the case, if the BeanParameter would be the only parameter.

**Comment by wuan** [comment]
In the case of a method with only a `@BeanParam` object containing only `@PathParam`s, there will be no schema. I think this is even more correct than before, because there is no need for schema in this case.
If we have a `@BeanParam` with payload (containing `@QueryParam` etc.) the behaviour is identical to the one without this PR.

**Comment by JoergAdler** [comment]
Ok. I'm not sure about it. As I got i right it should not matter, if a parameter ist a query or a path parameter. We have to be aware of this case here (GET with only one path parameter)

https://github.com/Mercateo/rest-jersey-utils/blob/master/src/main/java/com/mercateo/rest/jersey/utils/listing/AbstractListingResource.java

**Comment by JoergAdler** [comment]
for the record: (y)

**Pull request merged**
